#!/bin/bash
#init=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

echo Digete su correo electronico de midas

read email

ssh-keygen -t rsa -C @email

git clone https://github.com/laravel/homestead.git Homestead

cd $1

git clone https://github.com/midascashier/cashier_client.git new_client

cp $3/bin/config/* $1/new_client/config/

git clone https://github.com/midascashier/php-rabbitmq-test-app.git cashier_client_new_workers

cp $3/bin/config.php $1/cashier_client_new_workers/

cd $2/DevOps/new_cashier/Homestead
sh init.sh

cd $2/DevOps/new_cashier/
rm Homestead/Vagrantfile
rm Homestead/Homestead.yaml
cp Homestead.yaml Homestead
cp Vagrantfile Homestead
rm Vagrantfile
rm Homestead.yaml

read -t200 -n1 -r -p 'Press any key in the next five seconds...' key