/*
Navicat MySQL Data Transfer

Source Server         : Produccion Release
Source Server Version : 50619
Source Host           : midas-db2.im.priv:3306
Source Database       : midasone

Target Server Type    : MYSQL
Target Server Version : 50619
File Encoding         : 65001

Date: 2017-07-18 15:00:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `caBEUserPermission`
-- ----------------------------
DROP TABLE IF EXISTS `caBEUserPermission`;
CREATE TABLE `caBEUserPermission` (
  `caBEUserPermission_Id` int(10) NOT NULL AUTO_INCREMENT,
  `caBEUserPermissionGroup_Id` int(10) NOT NULL,
  `caBEUserPermissionType_Id` int(10) NOT NULL,
  `Code` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `Description` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `IsActive` tinyint(1) DEFAULT '1',
  `IsProtected` tinyint(1) DEFAULT '0',
  `EposAllowed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`caBEUserPermission_Id`),
  UNIQUE KEY `UNQ_Code` (`Code`) USING BTREE,
  KEY `FK_caBEUserPermission_caBEUserPermissionGroup` (`caBEUserPermissionGroup_Id`),
  KEY `FK_caBEUserPermission_caBEUserPermissionType` (`caBEUserPermissionType_Id`),
  CONSTRAINT `FK_caBEUserPermission_caBEUserPermissionGroup` FOREIGN KEY (`caBEUserPermissionGroup_Id`) REFERENCES `caBEUserPermissionGroup` (`caBEUserPermissionGroup_Id`),
  CONSTRAINT `FK_caBEUserPermission_caBEUserPermissionType` FOREIGN KEY (`caBEUserPermissionType_Id`) REFERENCES `caBEUserPermissionType` (`caBEUserPermissionType_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=697 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;

-- ----------------------------
-- Records of caBEUserPermission
-- ----------------------------
INSERT INTO `caBEUserPermission` VALUES ('1', '1', '8', 'MAIN_NAV_CUSTOMERS', 'Navegación principal de la sección de Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('2', '1', '8', 'MAIN_NAV_BOARD', 'Navegación principal para Revisar los distintos Board de Transacciones', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('3', '1', '8', 'MAIN_NAV_REPORTS', 'Navegación principal para la Consulta de Reporte', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('4', '1', '8', 'MAIN_NAV_FRAUD', 'Navegación principal de Fraude y Restricciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('5', '1', '8', 'MAIN_NAV_USERS', 'Navegación principal de Seguridad de Usuarios y Permisos', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('6', '1', '8', 'MAIN_NAV_BATCHES', 'Navegación principal de Batches', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('7', '90', '2', 'USER_MANAGEMENT_SEARCH', 'Administración de Usuarios', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('8', '90', '2', 'USER_MANAGEMENT_ADD', 'Permite Agregar Usuario', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('9', '90', '2', 'USER_MANAGEMENT_EDIT', 'Permite Editar Usuario', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('10', '90', '3', 'USER_MANAGEMENT_EDIT_SAVE', 'Permite Guarda los Cambios Realizados en el Usuario', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('11', '90', '3', 'USER_MANAGEMENT_EDIT_RESET_PASSWORD', 'Permite Modificar la Contraseña', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('12', '91', '2', 'USER_ROLE_MANAGEMENT_SEARCH', 'User role management page. Change role permissions', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('13', '91', '3', 'USER_ROLE_MANAGEMENT_SAVE', 'Permite Guarda los Cambios Realizados en el Rol', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('14', '92', '2', 'USER_PERMISSION_MANAGEMENT_SEARCH', 'User permission Management Page', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('15', '92', '3', 'USER_PERMISSION_MANAGEMENT_AUTHORIZE', 'Option to authorize and remove extra permissions', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('158', '120', '2', 'FRAUD_CUSTOMER_ACCOUNT_MANAGER_SEARCH', 'Opción para buscar cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('159', '122', '2', 'FRAUD_RESTRICTION_MANAGEMENT', 'Opción para buscar restricciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('160', '122', '3', 'FRAUD_RESTRICTION_MANAGEMENT_ADD', 'Opción para agregar restricciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('161', '122', '3', 'FRAUD_RESTRICTION_MANAGEMENT_DELETE', 'Opción para borrar restricciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('162', '121', '2', 'FRAUD_PREPAIDCARD_BIN_ADD', 'Opción para agregar un Bin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('163', '121', '3', 'FRAUD_PREPAIDCARD_BIN_REMOVE', 'Opción para remover BIN', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('164', '24', '2', 'REPORTS_ADVANCED_SEARCH', 'Opción para realizar consulta de Transacciones por Multiples Filtros', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('165', '25', '2', 'REPORTS_CREDITCARD_SEARCH', 'Opción para buscar tarjeta por Usuario, Dígitos y Descriptor', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('166', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_ALL_DIGITS_CC', 'Permiso para Ver TODOS los Dígitos de laTarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('167', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_FIRST_DIGITS_CC', 'Permiso para Ver los primeros 4 dígitos de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('168', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_LAST_DIGITS_CC', 'Permiso para Ver los últimos 4 dígitos de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('169', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_CVV', 'Permiso para Ver el CVV de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('170', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_SSN', 'Permiso para ver Número de Seguro Social (SSN)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('171', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_CUSTOMER_INFORMATION', 'Permiso para Ver la Información del Cliente desde Terminal', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('174', '4', '4', 'GLOBAL_PERMISSIONS_IGNORE_ALL_LIMITS', 'Permiso para IGNORAR todos los límites', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('211', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_PROCESSOR', 'Habilita Filtro: Procesadores', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('212', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_PROCESSOR_CLASS', 'Habilita Filtro: Clase de Procesadores', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('213', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_TRANSACTION_STATUS', 'Habilita Filtro: Estado de las Transacciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('214', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_TRANSACTION_TYPE', 'Habilita Filtro: Tipo de Transacciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('215', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_COMPANY', 'Habilita Filtro: Compañías', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('216', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_JOURNAL_ID', 'Habilita Filtro: Journal ID', '0', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('219', '24', '1', 'REPORTS_ADVANCED_SEARCH_RESULTS_LAYOUT_PROCESSORS', 'Resultado de Consulta para Processors', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('220', '24', '6', 'REPORTS_ADVANCED_SEARCH_FILTER_PROC_TRANS_ID', 'Habilita Filtro:  ProcTransID', '0', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('221', '24', '6', 'REPORTS_ADVANCED_SEARCH_FILTER_USERNAME', 'Habilita Filtro: UserName', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('228', '12', '2', 'BOARD_PAYOUTS', 'Board de Transacciones: Retiros', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('229', '121', '3', 'FRAUD_PREPAIDCARD_BIN_ADDS', 'Opcion para agregar BINS', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('231', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_CARD_HOLDER_NAME', 'Permiso para Ver el Nombre en la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('232', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_EXPIRATION_DATE', 'Permiso para Ver la Fecha de Expiración de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('233', '40', '8', 'TERMINAL', 'Menú de Terminales', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('234', '41', '8', 'TERMINAL_DEPOSIT', 'Submenú de Depositos en Terminales', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('235', '41', '2', 'TERMINAL_DEPOSIT_CC', 'Acceso a Depósitos con Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('236', '41', '2', 'TERMINAL_DEPOSIT_P2P', 'Acceso a Depósitos con WU/MG/RIA', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('237', '41', '2', 'TERMINAL_DEPOSIT_EW_TBEW', 'Acceso a Depósitos con TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('238', '43', '8', 'TERMINAL_MISC', 'Submenú de Miscelaneos en Terminales', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('239', '43', '2', 'TERMINAL_MISC_CC', 'Acceso a Miscelaneo de Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('240', '43', '2', 'TERMINAL_MISC_BANKWIRE', 'Acceso a Miscelaneo de BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('241', '43', '2', 'TERMINAL_MISC_GENCK', 'Acceso a Miscelaneo de Genck (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('242', '42', '8', 'TERMINAL_WITHDRAW', 'Submenú de Retiros en Terminales', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('243', '42', '2', 'TERMINAL_WITHDRAW_CC', 'Acceso a Retiros con Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('244', '42', '2', 'TERMINAL_WITHDRAW_P2P', 'Acceso a Retiros con WU/MG/RIA', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('245', '42', '2', 'TERMINAL_WITHDRAW_BANK_WIRE', 'Acceso a Retiros con BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('246', '42', '2', 'TERMINAL_WITHDRAW_GENCK', 'Acceso a Retiros con Genck (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('247', '42', '2', 'TERMINAL_WITHDRAW_NETELLER_NEW', 'Acceso a Retiros con Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('248', '42', '2', 'TERMINAL_WITHDRAW_SKRILL_EW', 'Acceso a Retiros con Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('249', '50', '8', 'DEFERRED', 'Menú de Diferidas', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('250', '51', '2', 'DEFERRED_DEPOSIT', 'Submenú de Depósitos Diferidos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('251', '51', '2', 'DEFERRED_DEPOSIT_CC', 'Acceso a Retiros Diferidos con Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('252', '53', '8', 'DEFERRED_MISC', 'Submenú de Depósitos Miscelaneos Diferidos', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('253', '53', '2', 'DEFERRED_MISC_BANKWIRE', 'Acceso a Miscelaneo Diferido con BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('254', '53', '2', 'DEFERRED_MISC_GENCK', 'Acceso a Miscelaneo Diferido con Genck (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('255', '52', '8', 'DEFERRED_WITHDRAW', 'Submenú de Retiros Diferidos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('256', '52', '2', 'DEFERRED_WITHDRAW_CC', 'Acceso a Retiros Diferidos con Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('257', '52', '2', 'DEFERRED_WITHDRAW_P2P', 'Acceso a Retiros Diferidos con WU/MG/RIA', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('258', '52', '2', 'DEFERRED_WITHDRAW_BANKWIRE', 'Acceso a Retiros Diferidos con BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('259', '52', '2', 'DEFERRED_WITHDRAW_GENCK', 'Acceso a Retiros Diferidos con Genck (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('260', '52', '2', 'DEFERRED_WITHDRAW_NETELLER', 'Acceso a Retiros Diferidos con Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('261', '52', '2', 'DEFERRED_WITHDRAW_MONEYBOOKERS', 'Acceso a Retiros Diferidos con Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('262', '60', '3', 'CC_PROCESS', 'Botón Proccesar Transacción de Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('263', '60', '3', 'CC_REMOVE', 'Boton Remover Tarjeta', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('264', '60', '3', 'CC_ADD', 'Botón Agregar en Tarjeta para Credit Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('265', '60', '3', 'CC_EDIT', 'Boton Editar en CC', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('266', '60', '5', 'CC_MANUAL_PROCESSOR', 'Listado de Procesadores de CC (Procesar Manual)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('267', '62', '3', 'P2P_PROCESS', 'Botón Proccesar Transacción de WU/MG/RIA', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('268', '62', '3', 'P2P_REMOVE', 'Boton Remover en  P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('269', '62', '3', 'P2P_ADD', 'Botón agregar en  P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('270', '62', '3', 'P2P_EDIT', 'Boton Editar en  P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('271', '62', '5', 'P2P_MANUAL_PROCESSOR', 'Listado de Procesadores de WU/MG/RIA  (Procesar Manual)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('272', '69', '3', 'TBL_PROCESS', 'Botón Proccesar Transacción de TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('273', '69', '3', 'TBL_REMOVE', 'Boton Remover en TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('274', '69', '3', 'TBL_ADD', 'Botón para Agregar en TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('275', '69', '3', 'TBL_EDIT', 'Boton Editar en  TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('276', '63', '3', 'BANKWIRE_PROCESS', 'Botón Proccesar Transacción de BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('277', '63', '3', 'BANKWIRE_REMOVE', 'Boton Remover en   BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('278', '63', '3', 'BANKWIRE_ADD', 'Botón agregar en  BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('279', '63', '3', 'BANKWIRE_EDIT', 'Boton Editar en  BankWire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('280', '64', '3', 'GENCK_PROCESS', 'Botón Proccesar Transacción de GenCK (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('281', '64', '3', 'GENCK_REMOVE', 'Botón para Remover en GenCK (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('282', '64', '3', 'GENCK_ADD', 'Botón para agregar en GenCK (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('283', '64', '3', 'GENCK_EDIT', 'Botón para Editar en  GenCK (BankDraft)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('284', '65', '3', 'NETELLER_PROCESS', 'Botón Proccesar Transacción de Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('285', '65', '3', 'NETELLER_REMOVE', 'Boton Remover en  Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('286', '65', '3', 'NETELLER_ADD', 'Botón para Agregar Cuenta de Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('287', '65', '3', 'NETELLER_EDIT', 'Boton Editar en  Neteller', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('288', '66', '3', 'SKRILL_PROCESS', 'Botón Proccesar Transacción de Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('289', '66', '3', 'SKRILL_REMOVE', 'Boton Remover en Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('290', '66', '3', 'SKRILL_ADD', 'Botón para Agregar Cuenta de Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('291', '66', '3', 'SKRILL_EDIT', 'Boton Editar en Skrill', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('293', '4', '4', 'GLOBAL_PERMISSIONS_UPDATE_PAYMETHOD', 'Permite Editar el Método de Pago desde Terminal', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('295', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_CHANGE_TO_APPROVED', 'Permite APROBAR la Transacción desde Journal Search', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('297', '4', '4', 'GLOBAL_PERMISSIONS_EDIT_CARD_NUMBER', 'Permite Editar el Número de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('302', '4', '4', 'GLOBAL_PERMISSIONS_EDIT_CARD_HOLDER_NAME', 'Permite Editar el Nombre de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('303', '4', '4', 'GLOBAL_PERMISSIONS_EDIT_EXPIRATION_DATE', 'Permite Editar la Fecha de Expiración de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('304', '4', '4', 'GLOBAL_PERMISSIONS_EDIT_CVV', 'Permite Editar CVV de la Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('306', '4', '4', 'GLOBAL_PERMISSIONS_REJECT_PAYMETHOD', 'Permite RECHAZAR una transacción desde Terminal', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('307', '53', '2', 'DEFERRED_MISC_CC', 'Acceso a Miscelaneo Diferido con Tarjeta de Crédito', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('308', '4', '1', 'GLOBAL_PERMISSIONS_VIEW_CUSTOMER_PASSWORD', 'Permite Ver la Contraseña del Cliente', '1', '1', '1');
INSERT INTO `caBEUserPermission` VALUES ('313', '20', '2', 'REPORTS_JOURNAL_SEARCH', 'Opción para realizar consulta de Multiples Journal ID/Midas ID', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('314', '21', '2', 'REPORTS_CUSTOMER_SEARCH', 'Opción para realizar consulta de Clientes', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('316', '28', '2', 'REPORTS_NEW_SIGN_UPS_SEARCH', 'Opción para realizar consulta de Cuentas Nuevas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('317', '22', '2', 'REPORTS_P2P_SEARCH', 'Opción para realizar consulta el Volumen de Transacciones de P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('318', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_TRANS_DETAILS', 'Permite ver los Detalles de la Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('319', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_FUND', 'Permite dar los Fondos de la Transacción a la Cuenta del Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('320', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_BONUS_APPLY', 'Permite Ver los detalles de los Bonos Aplicados a una Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('321', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_LIMIT_TRACE', 'Permite ver el Seguimiento de los Límites', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('322', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_CLERKS', 'Habilita Filtro: Clerks', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('323', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_CAPTURE', 'Permite realizar la Captura de una Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('324', '3', '7', 'CUSTOMER_CUSTOMER_RESTRICTION_TRACE', 'Permite ver el Seguimiento la Restricción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('325', '11', '2', 'BOARD_PENDING_PREAPPROVED', 'Board de Transacciones: Pre-Aprobadas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('326', '10', '2', 'BOARD_PENDING_DEPOSITS', 'Board de Transacciones: Depósitos Pendientes', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('327', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_CHANGE_TO_REJECTED', 'Permite RECHAZAR la Transacción desde Journal Search', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('328', '27', '2', 'REPORTS_FREEPLAY_SEARCH', 'Opción para realizar consulta de Freeplay', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('329', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_DOB', 'Editar Fecha de Nacimiento del Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('330', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_SSN', 'Editar Número de Seguro Social (SSN) del Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('331', '40', '2', 'TERMINAL_SUB_NAV_REPORT_PROBLEM', 'Permite Reportar la Transacción con Problemas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('332', '40', '2', 'TERMINAL_SUB_NAV_REJECT', 'Permite Rechazar la Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('333', '40', '2', 'TERMINAL_SUB_NAV_NOTES', 'Permite Ver las Notas de una Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('335', '4', '4', 'GLOBAL_PERMISSIONS_IGNORE_TIME_CONTROL', 'Permiso para IGNORAR el Tiempo de espera entre Transacciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('336', '26', '2', 'REPORTS_P2P_SEARCH_NAME', 'Opción para realizar consulta de Nombre de P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('337', '23', '2', 'REPORTS_P2P_NAMES_TRACE', 'Opción para realizar consulta de Names Trace de P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('338', '2', '7', 'OPEN_CUSTOMER_ACCOUNT', 'Permite Abrir un Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('339', '2', '7', 'OPEN_TRANSACTION_JOURNAL', 'Permite Abrir una Transacción por Journal ID', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('340', '2', '7', 'OPEN_TRANSACTION_ACUITYTEC', 'Permite Abrir una Transacción por AcuityTec ID', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('341', '3', '2', 'CUSTOMER_ACCOUNT_INFO', 'Permite Ver la Información de la Cuenta del Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('342', '3', '2', 'CUSTOMER_PERSONAL_INFO', 'Permite Ver la Información Personal del Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('343', '3', '2', 'CUSTOMER_LOGIN_ACTIVITY', 'Permite Ver las Últimos IPs accedidas por el Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('344', '3', '2', 'CUSTOMER_AVAILABLE_PROCESSORS', 'Permite Ver los Procesadores que se le Muestran al Cliente Online', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('346', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_ADD_NOTE', 'Permite AGREGAR Notas a una Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('347', '10', '3', 'EXPORT_PENDING_DEPOSIT', 'Permite Exportar del Board de Pending Deposit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('348', '11', '3', 'EXPORT_PENDING_PREAPPROVED', 'Permite Exportar del Board de Pre-Aprobadas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('349', '12', '3', 'EXPORT_PENDING_PAYOUTS', 'Permite Exportar del Board de Retiros', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('350', '3', '1', 'CUSTOMER_P2P_PENDING_MTCN', 'Permite Ver las Transacciones de P2P con Control Number Pendientes', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('351', '3', '1', 'CUSTOMER_LAST_TRANSACTIONS_ATTEMPTS', 'Permite Ver las Últimas Transacciones o Intentos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('352', '3', '1', 'CUSTOMER_CS_NOTES', 'Permite Ver las Notas de Customer Service (DGS)', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('353', '3', '1', 'CUSTOMER_MARKETING_NOTES', 'Permite Ver las Notas de Marketing (DGS)', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('354', '24', '3', 'REPORTS_ADVANCED_SEARCH_EXPORT', 'Permite Exportar las Transacciones a un Archivo Excel', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('355', '24', '1', 'REPORTS_ADVANCED_SEARCH_RESULTS_LAYOUT_FRAUD\r\n', 'Resultado de Consulta para Fraude', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('356', '24', '6', 'REPORTS_ADVANCED_SEARCH_FILTER_VIP', 'Habilita Filtro: VIP', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('358', '5', '3', 'TRANSACTION_APPLY_BONUS_NO_AVAILABLE', 'Permite APLICAR Bonos a una Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('360', '13', '2', 'BOARD_CANCELLED_PAYOUTS', 'Board de Transacciones: Payouts Cancelados', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('361', '13', '3', 'EXPORT_CANCELLED_PAYOUTS', 'Permite Exportar del Board de Payouts Cancelados', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('362', '5', '3', 'TRANSACTION_LIMIT_TRACE', 'Permite ver el proceso de la transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('363', '3', '2', 'CUSTOMER_ADDRESS_INFO', 'Permite Ver la Información del Domicilio del Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('364', '44', '8', 'TERMINAL_OTHER', 'Submenú de Otros Métodos en Terminales', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('365', '44', '2', 'TERMINAL_OTHER_PLAYER2PLAYER', 'Acceso a Transaferencias: Player2Player', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('366', '44', '2', 'TERMINAL_OTHER_FREEPLAY', 'Acceso para Dar Freeplay', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('367', '44', '2', 'TERMINAL_OTHER_BETPOINTS', 'Acceso a Canjear BetPoints', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('368', '5', '3', 'TRANSACTION_CHANGE_FEES', 'Permite Cambiar los Fees de la Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('369', '42', '2', 'TERMINAL_WITHDRAW_CRD3CO', 'Acceso a Retiros con EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('370', '42', '2', 'TERMINAL_WITHDRAW_BTCSCREEN', 'Acceso a Retiros con BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('371', '52', '2', 'DEFERRED_WITHDRAW_ECOPAYZ', 'Acceso a Retiros Diferidos con EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('372', '52', '2', 'DEFERRED_WITHDRAW_BITCOIN', 'Acceso a Retiros Diferidos con BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('373', '5', '3', 'TRANSACTION_CHANGE_TO_REJECT', 'Permite RECHAZAR la Transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('374', '61', '3', 'PAY2CARD_REMOVE', 'Boton Remover Tarjeta de Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('375', '61', '3', 'PAY2CARD_PROCESS', 'Botón Proccesar Transacción de Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('376', '61', '3', 'PAY2CARD_MANUAL_PROCESSOR', 'Listado de Procesadores de Pay2Card (Procesar Manual)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('377', '61', '3', 'PAY2CARD_ADD', 'Botón Agregar en Tarjeta para Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('378', '61', '3', 'PAY2CARD_EDIT', 'Boton Editar en Tarjeta Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('379', '71', '4', 'TERMINAL_OTHER_FREEPLAY_IGNORE_RESTRICTION', 'Permite Ignorar Restricciones para Freeplays', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('380', '68', '3', 'BITCOIN_PROCESS', 'Botón Proccesar Transacción de BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('381', '68', '3', 'BITCOIN_ADD', 'Botón para Agregar Cuenta de BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('382', '68', '3', 'BITCOIN_EDIT', 'Botón para Editar Cuenta BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('383', '68', '3', 'BITCOIN_REMOVE', 'Botón para Remover en Cuenta de BitCoin', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('384', '40', '2', 'TERMINAL_TRANSACTION_OPTION_MANUAL_PROCESSORS', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('386', '67', '3', 'ECOPAYZ_PROCESS', 'Botón Proccesar Transacción de EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('387', '67', '3', 'ECOPAYZ_ADD', 'Botón para Agregar Cuenta de EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('388', '67', '3', 'ECOPAYZ_EDIT', 'Botón para Editar Cuenta EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('389', '67', '3', 'ECOPAYZ_REMOVE', 'Botón para Remover en Cuenta de EcoPayz', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('390', '106', '2', 'BATCHES_PAY2CARD', 'Opción para consultar Batches de Pay2Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('391', '101', '2', 'BATCHES_SOLIDPAY', 'Opción para consultar Batches de SolidPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('392', '102', '2', 'BATCHES_TBL', 'Opción para consultar Batches de TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('393', '103', '2', 'BATCHES_WU', 'Opción para consultar Batches de WesternUnion', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('394', '104', '2', 'BATCHES_MG', 'Opción para consultar Batches de MoneyGram', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('395', '100', '3', 'BATCHES_CLOSE', 'Permite Cerrar y Exportar el Batch', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('396', '100', '3', 'BATCHES_EXPORT', 'Permite Exportar el Batch', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('405', '100', '3', 'BATCHES_REMOVE', 'Permite Remover Transacción del Batch', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('406', '70', '3', 'PLAYER2PLAYER_PROCESS', 'Botón Procesar las Transferencia entre Players', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('409', '24', '1', 'REPORTS_ADVANCED_SEARCH_RESULTS_LAYOUT_ACCOUNTING', 'Resultado de Consulta para Contabilidad', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('410', '4', '3', 'GLOBAL_PERMISSIONS_IGNORE_RESTRICTIONS', 'Permiso para IGNORAR todas las Restricciones', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('411', '123', '8', 'FRAUD_RESTRICTION_COMPANY_COUNTRY', 'Opción para limitar restricciones de compañía', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('412', '123', '8', 'FRAUD_RESTRICTION_COMPANY_STATE', 'Opción para limitar restricciones de compañia', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('413', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_ACCOUNT', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('414', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_BIN', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('415', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_EMAIL', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('416', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_IP', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('417', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_PROCESSOR', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('418', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_PROCESSOR_CLASS', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('419', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_ACCOUNT', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('420', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_BIN', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('421', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_COUNTRY', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('422', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_EMAIL', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('423', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_IP', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('424', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_LOYALTY', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('425', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_BOOK', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('426', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_STATE', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('427', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_AMOUNT', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('428', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_CLASS_COUNTRY', 'Opción para limitar restricciones de la clase del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('429', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_CLASS_EMAIL', 'Opción para limitar restricciones de la clase del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('430', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_CLASS_IP', 'Opción para limitar restricciones de la clase del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('431', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_CLASS_STATE', 'Opción para limitar restricciones de la clase del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('432', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_SKIN_COUNTRY', 'Opción para limitar restricciones del skin del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('433', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_SKIN_STATE', 'Opción para limitar restricciones del skin del procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('434', '123', '8', 'FRAUD_RESTRICTION_BOOK_COUNTRY', 'Opción para limitar restricciones de software provider', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('435', '123', '8', 'FRAUD_RESTRICTION_BOOK_PROCESSOR', 'Opción para limitar restricciones de software provider', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('436', '123', '8', 'FRAUD_RESTRICTION_BOOK_PROCESSOR_CLASS', 'Opción para limitar restricciones de software provider', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('437', '123', '8', 'FRAUD_RESTRICTION_BOOK_STATE', 'Opción para limitar restricciones de software provider', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('438', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_ACCOUNT', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('439', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_BIN', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('440', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_COUNTRY', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('441', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_EMAIL', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('442', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_IP', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('443', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_STATE', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('444', '123', '8', 'FRAUD_RESTRICTION_SYSTEM_BANK_SWIFT', 'Opción para limitar restricciones del sistema', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('445', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_DOCSONFILE', 'Edita el estado del Docs On File (Si/No)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('446', '42', '2', 'TERMINAL_WITHDRAW_DEBITCARDS', 'Acceso a Retiros con Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('448', '29', '2', 'REPORTS_PROCESSOR_TRANSACTION_SEARCH', 'Opción para realizar consulta por Processor Transaction Id', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('449', '3', '7', 'CUSTOMER_IMPORT', 'Permite Importar el Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('450', '105', '2', 'BATCHES_DEBITCARDS', 'Opción para consultar Batches DebitCard', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('451', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_NAME', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('452', '52', '2', 'DEFERRED_WITHDRAW_DEBITCARDS', 'Acceso a Retiros Diferidos con Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('453', '52', '2', 'DEFERRED_WITHDRAW_TBL', 'Acceso a Retiros Diferidos con TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('454', '42', '2', 'TERMINAL_WITHDRAW_EW_TBEW', 'Acceso a Retiros con TBL', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('456', '73', '3', 'DEBITCARDS_PROCESS', 'Botón Proccesar Transacción de Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('457', '73', '3', 'DEBITCARDS_REMOVE', 'Boton Remover en Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('458', '73', '3', 'DEBITCARDS_ADD', 'Botón para Agregar en Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('459', '73', '3', 'DEBITCARDS_EDIT', 'Boton Editar en Debit Cards', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('461', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_PROCESSOR_SKIN', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('462', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_UPDATE_TRANSACTION', 'Permite MODIFICAR Datos de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('463', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_UPDATE_P2P_INFO', 'Permite Modificar el Sender/Receiver de la transaccion', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('464', '30', '2', 'REPORTS_P2P_PAYOUT', 'Opción para realizar consulta de  P2P Payouts', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('467', '14', '2', 'BOARD_PENDING_TRANSFERS', 'Board de Transferencias', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('468', '14', '3', 'EXPORT_PENDING_TRANSFERS', 'Permite Exportar del Board de Transferencias Pendientes', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('469', '44', '2', 'TERMINAL_WITHDRAW_PLAYER2AGENT', 'Acceso a Transaferencias: Agent Transfers', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('470', '44', '2', 'TERMINAL_OTHER_PLAYER2PLAYER_BTC', 'Acceso a Transaferencias: Company Transfers', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('471', '54', '8', 'DEFERRED_OTHER', 'Submenú de Otros Métodos en Diferidas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('472', '54', '2', 'DEFERRED_OTHER_PLAYER2PLAYER', 'Acceso a Diferidas: Player2Player', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('473', '54', '2', 'DEFERRED_OTHER_PLAYER2PLAYER_BTC', 'Acceso a Diferidas: Company Transfers', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('474', '54', '2', 'DEFERRED_OTHER_PLAYER2AGENT', 'Acceso a Diferidas: Agent Transfers', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('475', '70', '3', 'PLAYER2PLAYER_ADD', 'Botón Activar las Transferencia entre Players', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('476', '74', '3', 'PLAYER2AGENT_PROCESS', 'Botón Procesar las Transferencia de Player a Agente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('477', '74', '3', 'PLAYER2AGENT_ADD', 'Botón Activar las Transferencias de Player a Agente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('478', '75', '3', 'PLAYER2PLAYERBTC_PROCESS', 'Botón Procesar las Transferencia entre Compañías', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('479', '75', '3', 'PLAYER2PLAYERBTC_ADD', 'Botón Activar las Transferencia entre Compañías', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('480', '31', '2', 'REPORTS_TRANSFERS_SEARCH', 'Opción para realizar consulta de Transaferencias', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('482', '31', '3', 'REPORTS_TRANSFERS_EXPORT', 'Permite Exportar las Transferencias a un Archivo Excel', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('483', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_IS_AGENT', 'Edita el si un cliente de Agente (Si/No)', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('484', '15', '2', 'BOARD_DECLINED_ATTEMPTS', 'Board: Declined Attempts', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('485', '54', '2', 'DEFERRED_OTHER_FREEPLAY', 'Acceso a Diferidas: FreePlays', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('486', '16', '2', 'BOARD_FREEPLAYS', 'Board: Pending FreePlays', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('487', '76', '2', 'TERMINAL_DEPOSIT_CASH', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('488', '42', '2', 'TERMINAL_WITHDRAW_CASH', 'Acceso a Retiros de cash en Locación', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('489', '52', '2', 'DEFERRED_WITHDRAW_CASH', 'Acceso a Retiros Diferidos de Cash en Locación', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('490', '76', '3', 'CASH_PROCESS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('491', '76', '3', 'CASH_ADD', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('492', '76', '3', 'CASH_EDIT', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('493', '76', '3', 'CASH_REMOVE', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('494', '77', '2', 'TERMINAL_DEPOSIT_BNK_TRANSFER', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('495', '77', '2', 'DEFERRED_DEPOSIT_BNK_TRANSFER', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('496', '42', '2', 'TERMINAL_WITHDRAW_BNK_TRANSFER', 'Permiso para PROCESAR retiros preaprobados de bank transfer', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('497', '52', '2', 'DEFERRED_WITHDRAW_BNK_TRANSFER_MENU', 'Acceso al Menu de Retiros Diferidos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('498', '77', '3', 'BNKTRANSFER_PROCESS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('499', '77', '3', 'BNKTRANSFER_ADD', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('500', '77', '3', 'BNKTRANSFER_EDIT', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('501', '77', '3', 'BNKTRANSFER_REMOVE', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('502', '32', '2', 'REPORTS_EPOS_BANK_TRANSFER_SEARCH', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('503', '33', '2', 'REPORTS_EPOS_SEARCH', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('504', '33', '5', 'EPOS_SEARCH_FILTER_STATUS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('505', '33', '5', 'EPOS_SEARCH_FILTER_TYPE', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('506', '33', '5', 'EPOS_SEARCH_FILTER_DEPARTMENT_USER', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('507', '33', '5', 'EPOS_SEARCH_FILTER_BANK', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('508', '33', '5', 'EPOS_SEARCH_FILTER_LOCATION', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('509', '33', '5', 'EPOS_SEARCH_FILTER_COUNTRY', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('510', '33', '5', 'EPOS_SEARCH_FILTER_USERNAME', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('511', '140', '2', 'MAIN_NAV_LOCATIONS', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('512', '140', '2', 'LOCATION_SEARCH', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('513', '140', '3', 'LOCATION_ADD', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('514', '140', '3', 'LOCATION_EDIT', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('515', '150', '2', 'MAIN_NAV_BANK', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('516', '150', '2', 'BANK_MANAGER', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('517', '150', '2', 'BANK_ACCOUNT_MANAGER', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('518', '150', '2', 'BANK_SEARCH', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('519', '150', '3', 'BANK_ADD', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('520', '150', '3', 'BANK_EDIT', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('521', '150', '2', 'BANK_EDIT_MESSAGE', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('522', '150', '2', 'BANK_ACCOUNT_SEARCH', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('523', '150', '3', 'BANK_ACCOUNT_ADD', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('524', '150', '3', 'BANK_ACCOUNT_EDIT', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('525', '150', '2', 'BANK_ACCOUNT_EDIT_FILTER', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('526', '150', '2', 'BANK_ACCOUNT_EDIT_DISPLAY', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('527', '17', '2', 'BOARD_EPOS_DEPOSITS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('528', '17', '3', 'EXPORT_EPOS_DEPOSITS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('529', '18', '2', 'BOARD_EPOS_PAYOUTS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('530', '18', '3', 'EXPORT_EPOS_PAYOUTS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('531', '123', '8', 'FRAUD_RESTRICTION_CUSTOMER_TRANS_TYPE', 'Opción para limitar restricciones de cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('532', '5', '3', 'TRANSACTION_P2P_SUBMIT', 'Permite confirmar un control number en P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('533', '5', '3', 'TRANSACTION_P2P_RESUBMIT', 'Permite re-enviar una transaction rechazada de P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('534', '5', '3', 'TRANSACTION_CHANGE_PRE_APPROVE', 'Permite PRE-APROBAR una transacción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('535', '42', '2', 'TERMINAL_WITHDRAW_BNK_TRANSFER_MENU', 'Permiso para CREAR retiros de bank transfer', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('536', '43', '2', 'TERMINAL_MISC_RECEIPT', 'Acceso a Miscelaneo Receipt', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('537', '53', '2', 'DEFERRED_MISC_RECEIPT', 'Acceso a Miscelaneo Receipt', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('538', '78', '3', 'MISCELLANEOUS_PROCESS', 'Botón Proccesar Transacción de Método Miscelaneo', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('539', '78', '3', 'MISCELLANEOUS_ADD', 'Boton para Habilitar el Método Miscelaneo', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('540', '78', '3', 'MISCELLANEOUS_EDIT', 'Boton para Editar el Método Miscelaneo', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('541', '78', '3', 'MISCELLANEOUS_REMOVE', 'Boton para Borrar (Inhabilitar) el Método Miscelaneo', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('542', '5', '3', 'TRANSACTION_ADD_REFERENCE', 'Permite agregarle una referencia a un retiro ya aprobado', '0', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('543', '43', '2', 'TERMINAL_MISCELLANEOUS', 'Acceso para Abrir Transacciones del Board Miscelaneas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('544', '3', '1', 'CUSTOMER_LIFETIME_TOTAL', 'Permite Ver el Lifetime Total del Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('550', '5', '3', 'CASH_TRANSACTION_ADD_REFERENCE', 'Permite agregarle una referencia a un retiro de cash ya aprobado', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('551', '5', '3', 'CASH_TRANSACTION_CHANGE_PRE_APPROVE', 'Permite Pre-Aprobar una transccion de Cash', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('552', '5', '3', 'BANK_TRANSACTION_CHANGE_PRE_APPROVE', 'Permite Pre-Aprobar una tranaccion de Bancos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('553', '5', '3', 'BANK_TRANSACTION_ADD_REFERENCE', 'Permite agregarle una referencia a un retiro de bancos ya aprobado', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('554', '5', '3', 'BNK_TRANSFER_BONUS_APPLY', 'Muestra el combo de bonus en el terminal de Bancos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('555', '5', '3', 'CASH_BONUS_APPLY', 'Muestra el combo de bonus en el terminal de cash', '0', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('556', '52', '2', 'DEFERRED_WITHDRAW_ASTROPAY', 'Acceso a Retiros Diferidos con AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('557', '42', '2', 'TERMINAL_WITHDRAW_ASTROPAY', 'Acceso a Retiros con AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('559', '79', '3', 'ASTROPAY_PROCESS', 'Botón Proccesar Transacción de AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('561', '79', '3', 'ASTROPAY_ADD', 'Botón para Agregar en AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('562', '79', '3', 'ASTROPAY_EDIT', 'Boton Editar en AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('563', '79', '3', 'ASTROPAY_REMOVE', 'Boton Remover en AstroPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('564', '42', '2', 'TERMINAL_WITHDRAW_CASH_MENU', 'Permiso para CREAR retiros de cash', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('565', '52', '2', 'DEFERRED_WITHDRAW_CASH_MENU', 'Acceso a Retiros Deferidos de CASH en Locación', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('566', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_ADD_ALERT', 'Permite Agregar Alertas a los Journal', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('567', '3', '2', 'CUSTOMER_GLOBAL_PERSONAL_INFO', 'Permite ver el resto de la informacion del Cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('568', '3', '2', 'CUSTOMER_GLOBAL_NAME', 'Permite ver el Nombre y Apellidos del cliente', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('569', '5', '3', 'TRANSACTION_GO_TO_BATCH', 'Permite ver la opción  Go To Batch de la transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('570', '5', '3', 'CUSTOMERS_CUSTOMER_ALERT_CHANGE_STATUS', 'Permite Cambiar el Activar|Desabilitar una alerta', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('571', '69', '2', 'ALWAYS_DISPLAY_TBL_WITHDRAW_OPTION', 'Permite ver siempre la opción de TBL en el menú de withdraw ', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('572', '58', '3', 'IDEBIT_PROCESS', 'Botón Procesar Transacción de IDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('573', '58', '3', 'IDEBIT_ADD', 'Botón para agregar en iDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('574', '58', '3', 'IDEBIT_EDIT', 'Botón para Editar en iDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('575', '58', '3', 'IDEBIT_REMOVE', 'Botón para Remover en iDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('576', '59', '3', 'INSTADEBIT_PROCESS', 'Botón Procesar Transacción de InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('577', '59', '3', '', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('578', '59', '3', 'INSTADEBIT_ADD', 'Botón para agregar en InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('579', '59', '3', 'INSTADEBIT_EDIT', 'Botón para Editar en InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('580', '59', '3', 'INSTADEBIT_REMOVE', 'Botón para Remover en InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('581', '42', '2', 'TERMINAL_WITHDRAW_IDEBIT', 'Acceso a Retiros con iDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('582', '42', '2', 'TERMINAL_WITHDRAW_INSTADEBIT', 'Acceso a Retiros con InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('583', '52', '2', 'DEFERRED_WITHDRAW_IDEBIT', 'Acceso a Retiros Diferidos con iDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('584', '52', '2', 'DEFERRED_WITHDRAW_INSTADEBIT', 'Acceso a Retiros Diferidos con InstaDebit', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('585', '24', '5', 'REPORTS_ADVANCED_SEARCH_FILTER_SP_COMPANY', 'Habilita Filtro: Book', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('586', '42', '2', 'TERMINAL_PAYOUT_MANUAL_CURRENCY_TO_PROCESSOR', 'Seleccionar manualmente la moneda enviada al procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('587', '77', '5', 'BNKTRANSFER_MANUAL_TRANSACTION_TYPE', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('588', '123', '8', 'FRAUD_RESTRICTION_PROCESSOR_CURRENCY', 'Opción para limitar restricciones de procesador', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('590', '19', '2', 'BOARD_CUSTOMER_REQUESTS', 'Board: Customer Requests', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('591', '3', '2', 'CUSTOMER_ADD_REQUEST', 'Allows the user to add a new customer request to the system', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('592', '3', '3', 'CUSTOMER_EDIT_REQUEST', 'Allows the user to edit a customer request in the system', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('593', '3', '3', 'CUSTOMER_PROCESS_REQUEST', 'Allows the user to process a customer request in the system', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('594', '5', '3', 'TRANSACTION_REFUND', 'Permite solicitar un refund para la transcción', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('595', '24', '3', 'REPORTS_ADVANCED_SEARCH_SUMMARY', 'Habilita la opción de solicitar el resumen ', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('596', '34', '2', 'REPORTS_FRAUD_SEARCH', 'Opción para realizar consulta de Transacciones rechazadas por restricciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('597', '34', '3', 'REPORTS_FRAUD_SEARCH_EXPORT', 'Permite Exportar las Transacciones a un Archivo Excel', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('598', '33', '3', 'EPOS_SEARCH_SUMMARY', 'Permite solicitar el resumen del reporte', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('601', '77', '6', 'BNKTRANSFER_CHANGE_PREAPPROVED_AMOUNT', 'Permiso para restringuir la modificación del monto de retiros ya preaprobados', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('602', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_CHANGE_STATUS', 'Permite cambiar el estado de una transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('603', '42', '2', 'TERMINAL_WITHDRAW_LOTTERYFUNDS', 'Acceso a Retiros de Lottery Funds', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('604', '42', '2', 'TERMINAL_WITHDRAW_LOTTERY_FUNDS_MENU', 'Permiso para CREAR retiros de lottery funds', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('605', '52', '2', 'DEFERRED_WITHDRAW_LOTTERY_FUNDS_MENU', 'Acceso a Retiros Deferidos de Lottery Funds', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('606', '5', '3', 'LOTTERYFUNDS_TRANSACTION_CHANGE_PRE_APPROVE', 'Permite Pre-Aprobar una transccion de Lottery Funds', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('609', '57', '2', 'TERMINAL_DEPOSIT_LOTTERY_FUNDS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('610', '57', '3', 'LOTTERYFUNDS_PROCESS', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('611', '57', '3', 'LOTTERYFUNDS_ADD', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('612', '57', '3', 'LOTTERYFUNDS_EDIT', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('613', '57', '3', 'LOTTERYFUNDS_REMOVE', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('614', '2', '7', 'OPEN_CUSTOMER_ACCOUNT_BY_CEDULA', '', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('615', '42', '2', 'TERMINAL_WITHDRAW_DINEROELECTRONICO', 'Acceso a Retiros con Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('616', '52', '2', 'DEFERRED_WITHDRAW_DINEROELECTRONICO', 'Acceso a Retiros Deferidos de Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('617', '56', '3', 'DINEROELECTRONICO_PROCESS', 'Botón Proccesar Transacción de Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('618', '56', '3', 'DINEROELECTRONICO_ADD', 'Botón para Agregar Cuenta de Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('619', '56', '3', 'DINEROELECTRONICO_EDIT', 'Botón para Editar Cuenta de Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('620', '56', '3', 'DINEROELECTRONICO_REMOVE', 'Botón para Remover en Cuenta de Dinero Electrónico', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('621', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_AUTHORIZATION_FORMS', 'Permite enviar los Formularios de Autorización al Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('622', '62', '3', 'P2P_FIND_PROCESSOR', 'Boton Encontrar Procesador en  P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('623', '60', '3', 'CC_FIND_PROCESSOR', 'Botón Encontrar Procesador para Credit Card', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('624', '5', '8', 'CUSTOMERS_CUSTOMER_DETAILS_CHANGE_STATUS_AMOUNT', 'Permite modificar el monto con el que una transacción será aprobada', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('625', '107', '2', 'BATCHES_BANKWIRE', 'Opción para consultar Batches de Bank Wire', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('626', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_ALLOW_MANUAL_FUNDING', 'Permite al Fondear Manualmente Transaccciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('628', '35', '2', 'REPORTS_CHARGEBACK_SEARCH', 'Opción para realizar consultas de transacciones con estado Chargeback', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('629', '108', '2', 'BATCHES_RIA', 'Opción para consultar Batches de Ria', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('631', '36', '2', 'REPORTS_PAYMENT_METHOD_SEARCH', 'Opción para realizar consultas de transacciones por medio de la cuenta', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('632', '93', '2', 'ACCESS_IP_MANAGEMENT', 'IP Access Management', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('633', '93', '3', 'ACCESS_IP_MANAGEMENT_ADD', 'IP Access Management Add Option', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('634', '94', '2', 'USER_ACTIVE_USER_SESSIONS', 'Allows access to the active user session screen', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('635', '94', '3', 'USER_ACTIVE_USER_SESSIONS_KICK', 'Grants access to kick out a user', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('636', '94', '3', 'USER_ACTIVE_USER_SESSIONS_DISABLE', 'Grants access to disable an user', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('637', '42', '2', 'TERMINAL_WITHDRAW_POSCASH', 'Acceso a Retiros termial de POSCASH', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('638', '76', '6', 'CASH_CHANGE_PREAPPROVED_AMOUNT', 'Permiso para restringuir la modificación del monto de retiros ya preaprobados', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('639', '57', '6', 'LOTTERYFUNDS_CHANGE_PREAPPROVED_AMOUNT', 'Permiso para restringuir la modificación del monto de retiros ya preaprobados', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('640', '55', '6', 'POSCASH_FUNDS_CHANGE_PREAPPROVED_AMOUNT', 'Permiso para restringuir la modificación del monto de retiros ya preaprobados', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('641', '3', '3', 'CUSTOMER_PHONE_VERIFICATION', 'Permite Verificar el número de teléfono del Cliente', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('642', '160', '2', 'MARKETING_PROCESSOR_DISPLAY', 'Permite ingresar a la opción para configurar el orden de los procesadores', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('643', '161', '3', 'MARKETING_PROCESSOR_DISPLAY_ADD', 'Permite agregar una nueva configuración', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('644', '161', '3', 'MARKETING_PROCESSOR_DISPLAY_EDIT', 'Permite cambiar la configuración seleccionada', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('645', '161', '3', 'MARKETING_PROCESSOR_DISPLAY_REMOVE', 'Permite eliminar la configuración seleccionada', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('646', '1', '8', 'MAIN_NAV_SETUP', 'Navegación principal de las opciones para Mercadeo', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('647', '109', '2', 'BATCHES_CK3', 'Opción para consultar Batches de CK3', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('648', '42', '2', 'TERMINAL_WITHDRAW_SAFETYPAY', 'Acceso a Retiros con SafetyPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('649', '52', '2', 'DEFERRED_WITHDRAW_SAFETYPAY', 'Acceso a Retiros Diferidos con SafetyPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('650', '80', '3', 'SAFETYPAY_PROCESS', 'Botón Proccesar Transacción de SafetyPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('651', '80', '3', 'SAFETYPAY_ADD', 'Botón para agregar en SafetyPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('652', '80', '3', 'SAFETYPAY_REMOVE', 'Boton Remover en SafetyPay', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('653', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_TRANS_DETAILS_CC', 'Permite ver el Request de la Transacción de Tarjetas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('654', '37', '2', 'REPORTS_REFUND_SEARCH', 'Opción para realizar consultas de transacciones con estado Refund', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('655', '15', '2', 'OPEN_TRANSACTION_ATTEMPT', 'Permite Abrir un Intento de Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('656', '70', '2', 'PLAYER2PLAYER_REGISTER_NEW_PLAYER', 'Acceso para Agregar una nueva cuenta transaferencias', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('657', '5', '3', 'CUSTOMERS_CUSTOMER_DETAILS_BIN_INFORMATION', 'Permite ver la Información de BIN de la tarjeta', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('658', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_PERSONAL_INFO', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('659', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_ADDRESS_INFO', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('660', '4', '3', 'GLOBAL_PERMISSIONS_EDIT_PERSONAL_ID', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('661', '4', '3', 'GLOBAL_PERMISSIONS_PLAYER_INFO_CHANGE_LOG', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('663', '38', '2', 'REPORTS_CC_SEARCH_VOLUME', 'Opción para realizar consulta el Volumen de Transacciones de CC', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('664', '3', '2', 'CUSTOMER_VERIFICATION_CODE_HISTORY', 'Permite Ver el historial de 2FA', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('665', '3', '3', 'CUSTOMER_EMAIL_VERIFICATION_CODE', 'Permite Ver el boton para habilitar el envio de email 2FA', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('666', '9', '2', 'BOARD_BANK_DEPOSITS', 'Permite ver el Board de Depósitos pendientes de Bancos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('667', '77', '3', 'BNKTRANSFER_KR_PROCESS', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('668', '77', '3', 'BNKTRANSFER_KR_ADD', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('669', '77', '3', 'BNKTRANSFER_KR_EDIT', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('670', '77', '3', 'BNKTRANSFER_KR_REMOVE', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('671', '77', '2', 'TERMINAL_WITHDRAW_BNK_TRANSFER_KR', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('672', '77', '2', 'TERMINAL_WITHDRAW_BNK_TRANSFER_KR_MENU', '', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('673', '9', '2', 'BOARD_BANK_PAYOUTS', 'Permite ver el Board de Retiros pendientes de Bancos', '1', '0', '1');
INSERT INTO `caBEUserPermission` VALUES ('674', '38', '2', 'REPORTS_PROCESSOR_FILTER', 'Permite ver el Reporte de Filtros del Procesador de Tarjetas', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('675', '60', '3', 'CUSTOMERS_CUSTOMER_DETAILS_CC_BLOCK_AUTHORIZE', 'Permite bloquear/autorizar CC desde la lista de payaccounts', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('676', '1', '8', 'MAIN_NAV_P2P', 'Navegación principal para P2P', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('677', '170', '2', 'P2P_BOARD_PENDING', 'Muestra las transacciones con estado pending', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('678', '170', '3', 'P2P_BOARD_PENDING_SAVE', 'Permite guardar cambios si son editados', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('679', '171', '2', 'P2P_BOARD_PROCESSING', 'Muestra las transacciones con estado processing', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('680', '171', '3', 'P2P_BOARD_PROCESSING_SAVE', 'Permite guardar cambios si son editados', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('681', '171', '3', 'P2P_BOARD_PROCESSING_CHANGE_PERSON', 'Permite Cambiar el Nombre de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('682', '171', '3', 'P2P_BOARD_PROCESSING_AUTHORIZE', 'Permite Autorizar la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('683', '172', '1', 'P2P_REPORT_TRANSACTION', 'Permite el Ingreso al Reporte de Transacciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('684', '172', '3', 'P2P_REPORT_TRANSACTION_SAVE', 'Permite Guardar los Cambios realizados a la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('685', '172', '4', 'P2P_REPORT_TRANSACTION_CHANGE_STATUS', 'Permite Cambiar el Estado de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('686', '172', '4', 'P2P_REPORT_TRANSACTION_CHANGE_AMOUNT', 'Permite Cambiar el Monto de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('687', '172', '4', 'P2P_REPORT_TRANSACTION_CHANGE_FEE', 'Permite Cambiar el Costo de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('688', '172', '4', 'P2P_REPORT_TRANSACTION_CHANGE_MTCN', 'Permite Cambiar el Control Number de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('689', '172', '3', 'P2P_REPORT_EXPORT', 'Permite Exportar las Transacciones', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('690', '172', '3', 'P2P_REPORT_TRANSACTION_GET_NEW_PERSON', 'Permite Cambiar el Nombre de la Transacción', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('691', '173', '2', 'P2P_NEW_TRANSACTION', 'Permite agragar una nueva transaccion', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('692', '174', '2', 'P2P_AVAILABLE_NAMES', 'Permite ver la lista de nombres disponibles y utilizados', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('693', '175', '2', 'P2P_TOTALS_SEARCH', 'Permite ver el reporte de Totales', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('695', '171', '4', 'P2P_TRANSACTION_IGNORE_LIMITS', 'Permite Ignorar los límites', '1', '0', '0');
INSERT INTO `caBEUserPermission` VALUES ('696', '160', '3', 'SETUP_ERROR_TRANSLATION', 'Permite Ingreso a la sección de Error Code', '1', '0', '0');
